package io.framework.actions;

/** Catalogue of driver actions whose platform support is gated by {@link ActionSupport}. */
public enum Action {
    // input
    TAP, DOUBLE_TAP, LONG_PRESS, TYPE, CLEAR, REPLACE, HIDE_KEYBOARD, PRESS_KEY,
    // gestures
    SWIPE, SCROLL, PINCH, ZOOM, DRAG_AND_DROP,
    // app lifecycle
    LAUNCH_APP, TERMINATE_APP, ACTIVATE_APP, BACKGROUND_APP, RESET_APP,
    // device
    ROTATE, LOCK, UNLOCK, SHAKE, SET_GEOLOCATION,
    TOGGLE_WIFI, TOGGLE_DATA, TOGGLE_AIRPLANE, NETWORK_THROTTLE,
    // system / messaging
    OPEN_NOTIFICATIONS, READ_NOTIFICATIONS, READ_SMS, SEND_SMS, SIMULATE_CALL,
    // permissions
    GRANT_PERMISSION, REVOKE_PERMISSION,
    // misc
    CLIPBOARD_GET, CLIPBOARD_SET, PUSH_FILE, PULL_FILE, DEEP_LINK, BIOMETRIC,
    SCREENSHOT, PAGE_SOURCE,

    // --- extended gestures ---
    TWO_FINGER_TAP, FLING, SCROLL_TO_ELEMENT, MULTI_TOUCH, DRAG, ROTATE_GESTURE,
    // extended input
    KEYEVENT, SELECT_PICKER_WHEEL,
    // extended device
    SET_ORIENTATION, GET_ORIENTATION, FREEZE_ROTATION, SCREEN_ON, SCREEN_OFF,
    IS_LOCKED, BATTERY_INFO, DEVICE_INFO, PRESS_HARDWARE_BUTTON,
    // extended system
    OPEN_QUICK_SETTINGS, GET_TOAST, REGISTER_WATCHER, SHELL_COMMAND,
    START_SCREEN_RECORDING, STOP_SCREEN_RECORDING, ELEMENT_SCREENSHOT, PULL_FOLDER,
    // extended app lifecycle
    INSTALL_APP, REMOVE_APP, IS_APP_INSTALLED, QUERY_APP_STATE, SWITCH_CONTEXT, GET_CONTEXTS,
    // alerts
    ACCEPT_ALERT, DISMISS_ALERT, GET_ALERT_TEXT,
    // iOS-specific
    SIRI_COMMAND, PERFORM_HID_EVENT, ENROLL_BIOMETRIC
}
